import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});
const inter = Inter({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});


export const metadata = {
  title: "one percent better | v1",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Welcome to my app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${poppins.className} bg-white px-2 lg:px-0 min-h-screen text-slate-800/90 antialiased`}
      >
        <main className="min-h-[calc(100dvh-4rem)] container mx-auto bg-white">
          <Navbar/>
          {children}
        </main>
          <Footer/>
      </body>
    </html>
  );

}

