import { Poppins } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import Footer from "./(ui)/components/Footer";
import Navbar from "./(ui)/components/Navbar";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});


export const metadata = {
  title: "O.P.B-v1",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  try {
    const session = await auth();

    return (
      <html lang="en">
        <head>
          <meta name="description" content="Welcome to my app" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body
          className={`${poppins.className} text-slate-700 overflow-x-hidden bg-white leading-none`}
        >
          <Navbar session={session} />
          <main className="min-h-[calc(100dvh-8rem)] mx-auto container p-4">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    );
  } catch (error) {
    console.error("Error in RootLayout:", error);
    return (
      <html lang="en">
        <body>
          <div>Error loading the application layout. Please refresh the page.</div>
        </body>
      </html>
    );
  }
}

